### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by EbenOladutemu** [danielkellyio/awake-template#1]
I'm getting  

> `ERROR  Cannot find module 'sharp'`

when I run npm run dev

**Comment by goomore** [comment]
- Try verify if `node_modules` is missing
- was there was an error during the `npm install` step
- is `sharp` definitely saved to the `package.json` dependencies?

**Comment by OladutemuEben** [comment]
- `node_moules` is present

- there were a couple of errors but all relating to `sharp`

- `sharp` is saved package.json

**Comment by goomore** [comment]
You already try `npm install sharp`? If yes, try post the erro message  here. Docs to https://www.npmjs.com/package/sharp

**Comment by OladutemuEben** [comment]
Yes I have done that. Even installed the particular version package.json stated. Errors everywhere.
All right would do that.

**Comment by danielkellyio** [comment]
Here are the install docs for sharp: https://github.com/lovell/sharp/blob/master/docs/install.md . Only thing that stands out to me is perhaps you need to update node if you're not on v8.5.0+ . Can look into the issue further if you're able to provide the exact errors you receive when trying to install.
