### ISSUE TITLE
How to disable news letter in config?

### ISSUE THREAD

**Issue by HeatMint** [danielkellyio/awake-template#11]
`newsletter: {
    on: false,
    heading: 'Subscribe to Our Newsletter',
    btnText: 'Subscribe',
    // Can be the form action on a mail chimp form, a hubspot form,
    // or any other url you want to post the form data to
    mailchimp: {
      on: true,
      formAction:
        'https://danielkelly.us3.list-manage.com/subscribe/post?u=d3c2e762b66a2353d0bc29bf3&amp;id=2abeaa06e0'
    },
    custom: {
      on: false,
      formAction: ''
    }
  },
`
Can't I just set on:false to disable that?

**Comment by Hitmasu** [comment]
Change to false should have worked. 

Are you sure thats not cache or similiar?

**Comment by TomFrink** [comment]
Have you tried removing `<news-letter-slide-out v-if="$siteConfig.newsletter.on" />` component from /layouts/default.vue?

**Comment by HeatMint** [comment]
I deleted the code of "subscribe to newsletter" button in index.vue with on:false set to fully disable it
