### ISSUE TITLE
Contact form erroring out

### ISSUE THREAD

**Issue by fairmontcreative** [danielkellyio/awake-template#12]
I've added the Netlify attribute to the form and am constantly experiencing this pattern:
-- Go to main page of website and navigate to contact page
-- URL is ~/contact
-- Fill out form, submit, get 404 error, go "back to our site" which brings back to contact page
-- URL gets adjusted to ~/contact/
-- Images don't load (show spinning graphic), fill out form and it successfully submits

**Comment by danielkellyio** [comment]
If anyone else is having this issue, try adding a hidden input with the name `form-name` and the value of whatever you want the form name to be in the netlify dashboard. Netlify automatically adds the input at build time but vue doesn't know anything about it and so when hydration occurs I think it's getting lost.
