### ISSUE TITLE
Can't add files via Netlify CMS

### ISSUE THREAD

**Issue by drewpterry** [danielkellyio/awake-template#17]
When you try to add a file via Netlify CMS in a blog post it sets the `featureImage` key without a leading `/` which will cause the image to not be found.

Netlify CMS will set the below key:

```
featureImage: uploads/purge-css-hero.jpg
```

However, it will only work if it is set like below:

```
featureImage: /uploads/purge-css-hero.jpg
```

**Comment by JimSadler** [comment]
I noticed this as well.

**Comment by danielkellyio** [comment]
Hmmm, that’s interesting. All the files saved here in the example content start with the leading slash. Maybe something’s changed on the Netlify CMS side. I’ll look more when I have the chance

**Comment by JimSadler** [comment]
an easy work around for this would be to edit the cms/netlify> static/admin > config.yml.
change public_folder: 'uploads'  to public_folder: '/uploads'

this fixes the issue

**Comment by danielkellyio** [comment]
thanks @JimSadler . That seems to take care of the issue
