### ISSUE TITLE
Images are not loading once you upload them

### ISSUE THREAD

**Issue by abhaytalreja** [danielkellyio/awake-template#18]
Thank you for an amazing project. I am definitely using this template. I had an issue when I tried to add any new categories or posts. The uploaded image doesn't show up on the post. Seems like it is not able to find the post. Can you please take a look at it?

Just clone the default project, deploy on netlify and add a new category and post.

Let me know if you need any more details.

**Comment by abhaytalreja** [comment]
I think I figured the problem with posts. It is cause, when we create the post through Netlify, the path in the .md file starts with 'upload/...' where as it should start with '/upload/...' - It is missing the relative path?

**Comment by JimSadler** [comment]
an easy work around for this would be to edit the cms/netlify> static/admin > config.yml.
change public_folder: 'uploads'  to public_folder: '/uploads'

this fixes the issue

**Comment by abhaytalreja** [comment]
Yup, got it to work last night. Thanks for the response!
