### ISSUE TITLE
How to change the SiteNavbar to Full screen Overlay Navigation

### ISSUE THREAD

**Issue by boruto99** [danielkellyio/awake-template#19]
I want to change the navbar to full screen overlay navbar. Can you give me some nutrition to improve my web...

best regards.

**Comment by danielkellyio** [comment]
Currently there is no setting to flip that supports that but you should be able to customize the menu however you desire in components/siteNav.vue. Maybe could implement something like this video I found with a google search https://m.youtube.com/watch?v=IdrXb0twu70

Good luck 😀 let me know if you have anymore questions
