### ISSUE TITLE
og:image is returning a 404

### ISSUE THREAD

**Issue by haghdk** [danielkellyio/awake-template#21]
I am trying to use an image for the og:image meta tag on blog posts, but is doesn't work, I think because of the hash-renaming of the feature image on a blog post.

The tag looks like this
`<meta data-n-head="true" data-hid="og:image" property="og:image" content="https://www.domain.com/uploads/image.jpg"> `But that returns a 404-error because the image is renamed to hash-size and has the path of "/_nuxt/uploads/646f87d-1280.jpg" - or is it me that do it wrong?

**Comment by danielkellyio** [comment]
it is because of the hash. When you are referencing that image try using the require function. 
Example here: https://github.com/danielkellyio/awake-template/blob/master/components/cards/GenericCard.vue#L72

**Comment by haghdk** [comment]
I fixed it by using your recommendation
