### ISSUE TITLE
404 during grid items loading

### ISSUE THREAD

**Issue by danielleeman** [danielkellyio/awake-template#22]
GET https://awake-template.netlify.com/api/posts/page-3.json 404

On the home page, loading related posts, etc. I thought it was perhaps a modification I made, but on the demo site it's the same issue.

**Comment by danielkellyio** [comment]
it's because of the way I've done the lazy load. It keeps asking for pages until it asks for a page that doesn't exist and then it stops asking (because there are only 2 pages). So when it gets to the end it will always show an ajax request error
