### ISSUE TITLE
error in embed video

### ISSUE THREAD

**Issue by iukones** [danielkellyio/awake-template#23]
Hi Daniel, I have problems to insert YouTube videos directly in the Rich Tex editor, in the preview it shows the player, but when performing the deploy it only shows the iframe code, is it a limitation of the template?

**Comment by danielkellyio** [comment]
the template escapes html by default. Markdown in the template is rendered by the markdown-it library found here: https://github.com/markdown-it/markdown-it . You can allow html in the markdown-it settings like so: `html: true`. See `components/Markdown.vue` lines 18 -20. 

Just realize that this opens up the editor to any and all html including script tags which maybe be unsafe depending on who has access to make changes through the admin interface.

**Comment by iukones** [comment]
> la plantilla escapa html por defecto. Markdown en la plantilla se representa mediante la biblioteca markdown-it que se encuentra aquí: https://github.com/markdown-it/markdown-it . Puede permitir HTML en la reducción del precio-configuración que de este modo: `html: true`. Ver `components/Markdown.vue`líneas 18-20.
> 
> Solo tenga en cuenta que esto abre el editor a todos y cada uno de los html, incluidas las etiquetas de script que pueden ser inseguras dependiendo de quién tiene acceso para realizar cambios a través de la interfaz de administración.

excellent, thanks a lot Daniel...
