### ISSUE TITLE
undefined blog posts hrefs on page load

### ISSUE THREAD

**Issue by haghdk** [danielkellyio/awake-template#24]
When the page loads, blog posts and categories will have their `a hrefs` set to /undefined until posts have been loaded. When using a SEO analyzer for example that will trigger a 404 error and as a result a lower SEO score.

**Comment by danielkellyio** [comment]
fixed with this commit: https://github.com/danielkellyio/awake-template/pull/28/commits/73ba59c0340dbffe2a0b637f7705b3755fb324f3

let me know if you have any more issues. Thanks!
