### ISSUE TITLE
Can't access Netlify CMS locally

### ISSUE THREAD

**Issue by tuttiq** [danielkellyio/awake-template#25]
No matter what configurations I set, when I try to access `/admin` I get a routing error (trying to open `admin.md` post that doesn't exist). Anyone else was able to access the CMS on local environment?

![Screen Shot 2020-03-19 at 12 24 50 PM](https://user-images.githubusercontent.com/1096046/77028702-f4436300-69dc-11ea-9d58-58dc7b07958a.png)

**Comment by danielkellyio** [comment]
this commit should fix the issue: https://github.com/danielkellyio/awake-template/pull/27/commits/7536bbb98120676bbf65b03ec3209bda166184c4

Thanks! Let me know if you have any more issues!

(Ps. took a look at https://tuttiq.me/ and I've love what you've done with it!!)

**Comment by tuttiq** [comment]
Thank you!
