### ISSUE TITLE
How to change default colours

### ISSUE THREAD

**Issue by cameronwickes** [danielkellyio/awake-template#26]
I can't seem to change the default colours for the theme. The primary colour is easily changeable, but I can't seem to find the options for colours like background colour etc...
Thanks!

**Comment by danielkellyio** [comment]
all available color variables are set here: https://github.com/danielkellyio/awake-template/blob/master/assets/scss/_vars.scss

if you would like any further customization of colors you will have to write the css for that yourself. 
Thanks!
