### ISSUE TITLE
error logging into /admin with Netlify identity.

### ISSUE THREAD

**Issue by BobWalsh** [danielkellyio/awake-template#3]
Got this error on Netlify when I attempted to go to  https://vibrant-bassi-82afc8.netlify.com/admin/#/ )the forked repo of Awake I' transforming into my blog.
<img width="709" alt="Cursor_and_Awake___Content_Manager" src="https://user-images.githubusercontent.com/5097/64131966-0cc19800-cd81-11e9-8df8-4f75e77c9d05.png">

What am I missing Daniel?

**Comment by BobWalsh** [comment]
Yep - this was a Netlify issue: you have to enable Identity, and invite yourself. Do you want a PR on this?

**Comment by BobWalsh** [comment]
... and you have to enable Netlify’s Git Gateway (connects your site to GitHub’s API. This allows users of tools like NetlifyCMS to work with content, branches, and pull requests without needing a GitHub account.) - which is next to impossible to find.

**Comment by danielkellyio** [comment]
sure thing, @BobWalsh a PR would be great! Thanks!

**Comment by danielkellyio** [comment]
updated getting started docs to account for Netlify Identity setup
commit #b3cc4fbc661059967b6384d8cf0f80a306e93d27
