### ISSUE TITLE
Google Analytics broken

### ISSUE THREAD

**Issue by bpmct** [danielkellyio/awake-template#33]
I'm pretty sure the analytics feature is broken... I tried looking into it myself but wasn't able to find anything. Would you be able to replicate?

**Comment by danielkellyio** [comment]
Yeah, now that you mention it my analytics data for the template site hasn't been coming in for a bit. The config for @nuxtjs/google-analytics looks fine but one of the libs that it relies on ([vue-analytics](https://www.npmjs.com/package/vue-analytics)) has this warning:
<img width="765" alt="Screen Shot 2020-05-06 at 8 51 26 PM" src="https://user-images.githubusercontent.com/7635209/81245721-5bdc5e80-8fdb-11ea-80dd-754a218e1f72.png">

Looks like google has rolled out some ga alternative. I'll check into maybe using that instead

**Comment by danielkellyio** [comment]
this seems to fix it: https://github.com/danielkellyio/awake-template/pull/34

**Comment by bpmct** [comment]
Thanks, Daniel. I really appreciate this!
