### ISSUE TITLE
Kindly add Dark Mode with toggle

### ISSUE THREAD

**Issue by stephenajulu** [danielkellyio/awake-template#44]
Hi, how are you?
This is a great theme. Thank you.
Could you kindly add Dark Mode with a toggle and an option to use dark mode(or light mode) as default?
Have a great day.

**Comment by danielkellyio** [comment]
I don't currently have the time to add in this feature but official Nuxt blog has a post about doing just that if you'd like to use it as a guide. https://nuxtjs.org/blog/going-dark-with-nuxtjs-color-mode.

If you get this working feel free to open a PR. Thanks!
