### ISSUE TITLE
Inline SVGs in posts

### ISSUE THREAD

**Issue by PNRxA** [danielkellyio/awake-template#45]
Currently nuxt-responsive-loader doesn't support SVG and the images will show "image not found". 

Is there a way to include SVG images in posts without it being processed by nuxt-responsive-loader?

**Comment by danielkellyio** [comment]
Images are required via the responsive loader in `useResponsiveImages` method in the `Markdown` component. You could add a condition there to exclude svg's from going through responsive loader. If you get this working, feel free to create a PR! Thanks!

https://github.com/danielkellyio/awake-template/blob/master/components/Markdown.vue#L36-L59

**Comment by PNRxA** [comment]
@danielkellyio thanks for the guidance, sorry to bother you about this but is there an easy way to allow routing to images directly in the uploads directory? It's the last thing I can't figure out, I've got it working but the direct link to images 404
