### ISSUE TITLE
Using .vue instead of .md for blog posts

### ISSUE THREAD

**Issue by hurnhu** [danielkellyio/awake-template#50]
Im somewhat new to Nuxtjs, but i was wondering if it is possible to use .vue files for the blog posts instead of .md files?

**Comment by danielkellyio** [comment]
Vue files would not be supported. Netlify CMS has to be able to read your content files, therefore the content files must be in one of the formats supported by Netlify CMS: https://www.netlifycms.org/docs/configuration-options/#collections

Depending on your use case however, you might be able to make a custom widget or custom editor component in netlify cms that can output a view component of your choice. 
https://www.netlifycms.org/docs/custom-widgets/
