### ISSUE TITLE
Modify destination email in contact form

### ISSUE THREAD

**Issue by ChilledChild** [danielkellyio/awake-template#59]
I'm looking to modify the destination email for the contact form under the default "contact us" page.
I would have anticipated that this would be located in awake-template/components/ContactForm.vue , though this only modifies the visible elements.

**Comment by PNRxA** [comment]
I believe you're meant to take this into your own hands. The easiest solution is to hand it off to Netlify Forms. Here's a ContactForm.vue which will do this (after changing your contact form, activate Netlify forms from Netlify admin):

```javascript
<template>
  <form name="contact" method="POST" data-netlify="true">
    <!-- Name -->
    <div class="field">
      <label class="label is-medium">Name</label>
      <div class="control has-icons-left">
        <input
          class="input is-medium"
          type="text"
          name="name"
          placeholder="John Smith"
        />
        <span class="icon is-small is-left">
          <font-awesome-icon icon="user" />
        </span>
      </div>
    </div>
    <!-- Email -->
    <div class="field">
      <label class="label is-medium">Email</label>
      <div class="control has-icons-left">
        <input
          class="input is-medium"
          type="email"
          name="email"
          placeholder="you@email.com"
        />
        <span class="icon is-small is-left">
          <font-awesome-icon icon="envelope" />
        </span>
      </div>
    </div>
    <!-- Subject -->
    <div class="field">
      <label class="label is-medium">Subject</label>
      <div class="control has-icons-left">
        <input
          class="input is-medium"
          type="text"
          name="subject"
          placeholder="Brief Summary"
        />
        <span class="icon is-small is-left">
          <font-awesome-icon icon="briefcase" />
        </span>
      </div>
    </div>
    <!-- Message -->
    <div class="field">
      <label class="label is-medium">Message</label>
      <div class="control">
        <textarea
          name="message"
          class="textarea"
          placeholder="Detailed description of your comment, request, etc"
          rows="8"
        ></textarea>
      </div>
    </div>
    <div class="control" type="submit">
      <button class="button is-primary">
        Contact Us
      </button>
    </div>
  </form>
</template>
```

**Comment by ChilledChild** [comment]
This appears to create submissions! ~~Interestingly after selecting submit, the page refreshes with no confirmation that the form was sent, recent articles and media do not load, along with navigating to other pages. Filling out the form a second time will complete the submission successfully, though I can't imagine a form should have to be filled twice. This appears to only work if the URI contains a trailing slash.~~

After following this format, any submission results in "Page not found" from Netlify. Adding a trailing slash to the URI fixes this, but no media elements or other content will properly load.
